/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DEPRECATED: use `materialization` instead. `materialization` accepts the same shorthand strings ("incremental" | "ephemeral") plus the full object form for `format` / `partitions` / `strategy` configuration. Replace `"materialized": "incremental"` with `"materialization": "incremental"`.
 */
export type SchemaModelMaterialized = 'ephemeral' | 'incremental';
