/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bundles the framework-injection opt-outs into one flag. "columns" implies exclude_datetime + exclude_portal_partition_columns + exclude_portal_source_count (the auto WHERE date filters still fire). "all" additionally implies exclude_date_filter. Individual exclude flags at the same scope override this flag (set exclude_portal_source_count: false to keep that one column even when this is "all"). Mutually exclusive with from.rollup when the resolved value implies exclude_datetime (validator errors).
 */
export type SchemaModelExcludeFrameworkArtifacts = 'all' | 'columns';
