/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DEPRECATED: use `materialization.strategy` instead. Replace top-level `"incremental_strategy": { "type": "delete+insert" }` with `"materialization": { "type": "incremental", "strategy": { "type": "delete+insert" } }`. Wraps the shared strategy shape (`model.incremental_strategy.schema.json`) so the deprecation hint applies only when the field is authored at the model top level, not when it's nested under `materialization.strategy` (the canonical, non-deprecated location).
 */
export type SchemaModelIncrementalStrategyDeprecatedTopLevelField =
  IncrementalStrategy;
/**
 * Incremental Strategy for dbt-trino. Pick one of: 'append', 'delete+insert', 'merge', 'overwrite_existing_partitions', 'dj_iceberg_partition_overwrite'. NOTE: 'overwrite_existing_partitions' requires a custom dbt macro in your project and is not shipped by the DJ (Data JSON) Framework. 'merge' and 'dj_iceberg_partition_overwrite' require the target table to use Iceberg format in dbt-trino. When in doubt, use 'delete+insert' with a partition column as unique_key.
 */
export type IncrementalStrategy =
  | {
      /**
       * Append rows without de-duplication.
       */
      type: 'append';
    }
  | {
      /**
       * Delete rows matching unique_key, then insert.
       */
      type: 'delete+insert';
      /**
       * Override the unique key(s) to use for delete+insert. Defaults to the model's partition column when omitted.
       */
      unique_key?: string | [string, ...string[]];
    }
  | {
      /**
       * Row-level upsert on unique_key. Requires Iceberg in dbt-trino.
       */
      type: 'merge';
      /**
       * The unique key(s) to use for merging.
       */
      unique_key: string | [string, ...string[]];
      /**
       * The columns to exclude when merging.
       */
      merge_exclude_columns?: string[];
      /**
       * The columns to update when merging.
       */
      merge_update_columns?: string[];
    }
  | {
      /**
       * Overwrite only the partitions in the new slice. REQUIRES a custom macro in your dbt project — prefer 'delete+insert' if you do not have one.
       */
      type: 'overwrite_existing_partitions';
    }
  | {
      /**
       * Overwrite only the partitions in the new slice on an Iceberg table. Shipped by DJ; requires Iceberg format.
       */
      type: 'dj_iceberg_partition_overwrite';
    };
