/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * DEPRECATED: use `materialization.partitions` instead. Replace `"partitioned_by": ["col"]` with `"materialization": { "type": "incremental", "partitions": ["col"] }`.
 *
 * @minItems 1
 */
export type SchemaModelPartitionedBy = [
  SchemaColumnName,
  ...SchemaColumnName[],
];
/**
 * Validate column name
 */
export type SchemaColumnName = string;
