/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate group reference
 */
export type SchemaModelGroup = string;
/**
 * Validate model topic
 */
export type SchemaModelTopic = string;
/**
 * Validate model name
 */
export type SchemaModelName = string;
/**
 * Description for the model that will appear as a hover tooltip in Lightdash
 */
export type SchemaModelDescription = string;
/**
 * Whether this column should be treated as case-sensitive
 */
export type SchemaLightdashCaseSensitive = boolean;
/**
 * Schema for lightdash AI hints
 */
export type SchemaLightdashAIHint = string | string[];
/**
 * Schema for lightdash required filters
 */
export type SchemaLightdashRequiredFilters = {
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string;
}[];
/**
 * Validate Lightdash metric name
 */
export type SchemaLightdashMetricName = string;
/**
 * Validate model tags
 */
export type SchemaModelTags = (
  | string
  | {
      tag: string;
      type?: 'ai_hints' | 'exclude' | 'inherit' | 'local';
    }
)[];
/**
 * Validate model data_tests
 */
export type SchemaModelDataTests = (
  | {
      /**
       * Validates that all values in the specified column are unique (no duplicates).
       */
      type: 'unique';
      /**
       * Name of the column to test for uniqueness (e.g., 'id', 'email')
       */
      column_name: string;
    }
  | {
      /**
       * Validates that row count equals parent model (detects unintended 1-to-many relationships). Requires portal_partition_daily column.
       */
      type: 'equal_row_count';
      /**
       * Parent model to compare against. Use ref() syntax, e.g., ref('parent_model_name')
       */
      compare_model: string;
      /**
       * Type of join used (e.g., 'left', 'inner'). Test only runs for specified join types.
       */
      join_type?: string;
    }
  | {
      /**
       * Validates that the SUM of an aggregate column is not NULL for any date partition. This catches partitions where all values are NULL or missing. Use for fact columns in rollup/aggregation models to ensure complete data.
       */
      type: 'no_null_aggregates';
      /**
       * Name of the aggregate column to test (e.g., 'total_amount', 'record_count')
       */
      column_name: string;
      /**
       * Column to use for date filtering. Defaults to 'portal_partition_daily' if not specified.
       */
      date_filter_column?: string;
      /**
       * Data type of the date filter column. Affects how date filtering is applied.
       */
      date_filter_type?: 'date' | 'timestamp' | 'string' | 'number';
    }
  | {
      /**
       * Validates that row count is less than or equal to parent model. Use for joins with filtering conditions. Requires portal_partition_daily column.
       */
      type: 'equal_or_lower_row_count';
      /**
       * Parent model to compare against. Use ref() syntax, e.g., ref('parent_model_name')
       */
      compare_model: string;
      /**
       * Type of join used (e.g., 'left', 'inner'). Optional, for documentation purposes.
       */
      join_type?: string;
    }
)[];
/**
 * Materialization Configuration
 */
export type SchemaModelMaterialization =
  | 'incremental'
  | 'ephemeral'
  | {
      type: 'ephemeral';
    }
  | {
      type: 'incremental';
      database?: SchemaModelDatabase;
      format?: SchemaModelFormat;
      partitions?: SchemaModelPartitions;
      strategy?: IncrementalStrategy;
    };
/**
 * Database override for where the model will be materialized
 */
export type SchemaModelDatabase = string;
/**
 * Open table format for the model
 */
export type SchemaModelFormat = 'delta_lake' | 'hive' | 'iceberg';
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Override the default partitioneds configuration for this model
 */
export type SchemaModelPartitions = SchemaColumnName[];
/**
 * Incremental Strategy for dbt-trino. Pick one of: 'append', 'delete+insert', 'merge', 'overwrite_existing_partitions', 'dj_iceberg_partition_overwrite'. NOTE: 'overwrite_existing_partitions' requires a custom dbt macro in your project and is not shipped by the DJ (Data JSON) Framework. 'merge' and 'dj_iceberg_partition_overwrite' require the target table to use Iceberg format in dbt-trino. When in doubt, use 'delete+insert' with a partition column as unique_key.
 */
export type IncrementalStrategy =
  | {
      /**
       * Append rows without de-duplication.
       */
      type: 'append';
    }
  | {
      /**
       * Delete rows matching unique_key, then insert.
       */
      type: 'delete+insert';
      /**
       * Override the unique key(s) to use for delete+insert. Defaults to the model's partition column when omitted.
       */
      unique_key?: string | [string, ...string[]];
    }
  | {
      /**
       * Row-level upsert on unique_key. Requires Iceberg in dbt-trino.
       */
      type: 'merge';
      /**
       * The unique key(s) to use for merging.
       */
      unique_key: string | [string, ...string[]];
      /**
       * The columns to exclude when merging.
       */
      merge_exclude_columns?: string[];
      /**
       * The columns to update when merging.
       */
      merge_update_columns?: string[];
    }
  | {
      /**
       * Overwrite only the partitions in the new slice. REQUIRES a custom macro in your dbt project — prefer 'delete+insert' if you do not have one.
       */
      type: 'overwrite_existing_partitions';
    }
  | {
      /**
       * Overwrite only the partitions in the new slice on an Iceberg table. Shipped by DJ; requires Iceberg format.
       */
      type: 'dj_iceberg_partition_overwrite';
    };
/**
 * DEPRECATED: use `materialization` instead. `materialization` accepts the same shorthand strings ("incremental" | "ephemeral") plus the full object form for `format` / `partitions` / `strategy` configuration. Replace `"materialized": "incremental"` with `"materialization": "incremental"`.
 */
export type SchemaModelMaterialized = 'ephemeral' | 'incremental';
/**
 * DEPRECATED: use `materialization.strategy` instead. Replace top-level `"incremental_strategy": { "type": "delete+insert" }` with `"materialization": { "type": "incremental", "strategy": { "type": "delete+insert" } }`. Wraps the shared strategy shape (`model.incremental_strategy.schema.json`) so the deprecation hint applies only when the field is authored at the model top level, not when it's nested under `materialization.strategy` (the canonical, non-deprecated location).
 */
export type SchemaModelIncrementalStrategyDeprecatedTopLevelField =
  IncrementalStrategy;
/**
 * DEPRECATED: use `materialization.partitions` instead. Replace `"partitioned_by": ["col"]` with `"materialization": { "type": "incremental", "partitions": ["col"] }`.
 *
 * @minItems 1
 */
export type SchemaModelPartitionedBy = [
  SchemaColumnName,
  ...SchemaColumnName[],
];
/**
 * Exclude Daily Filter
 */
export type ModelExcludeDailyFilterSchemaJson = boolean;
/**
 * Will prevent the automatic date filters from getting added
 */
export type SchemaModelExcludeDateFilter = boolean;
/**
 * Will prevent the automatic portal partition date columns from getting added
 */
export type SchemaModelExcludePortalPartitionColumns = boolean;
/**
 * Skips auto-injection of the `datetime` column from the upstream model. Independent of `exclude_portal_partition_columns` -- partition columns survive unless that flag is also set. Mutually exclusive with `from.rollup`, which exists to produce a `datetime` column. For pure-dimension or lookup models, set both `exclude_datetime` and `exclude_portal_partition_columns` to true.
 */
export type SchemaModelExcludeDatetime = boolean;
/**
 * Bundles the framework-injection opt-outs into one flag. "columns" implies exclude_datetime + exclude_portal_partition_columns + exclude_portal_source_count (the auto WHERE date filters still fire). "all" additionally implies exclude_date_filter. Individual exclude flags at the same scope override this flag (set exclude_portal_source_count: false to keep that one column even when this is "all"). Mutually exclusive with from.rollup when the resolved value implies exclude_datetime (validator errors).
 */
export type SchemaModelExcludeFrameworkArtifacts = 'all' | 'columns';
/**
 * Will prevent the automatic portal source count column from getting added
 */
export type SchemaModelExcludePortalSourceCount = boolean;
/**
 * Validate model ids
 */
export type SchemaModelRef = string;

/**
 * Validates schema for rollup models
 */
export interface SchemaModelTypeIntRollupModel {
  type: 'int_rollup_model';
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  meta?: SchemaModelMeta;
  data_tests?: SchemaModelDataTests;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: SchemaModelIncrementalStrategyDeprecatedTopLevelField;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_datetime?: SchemaModelExcludeDatetime;
  exclude_framework_artifacts?: SchemaModelExcludeFrameworkArtifacts;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  from: {
    model: SchemaModelRef;
    rollup: SchemaModelFromRollup;
  };
}
/**
 * Validates schema for setting lightdash properties at the model level
 */
export interface SchemaModelLightdash {
  case_sensitive?: SchemaLightdashCaseSensitive;
  table?: SchemaLightdashTable;
  metrics?: SchemaLightdashMetric[];
  metrics_exclude?: SchemaLightdashMetricName[];
  metrics_include?: SchemaLightdashMetricName[];
}
export interface SchemaLightdashTable {
  ai_hint?: SchemaLightdashAIHint;
  group_details?: SchemaLightdashGroupDetails;
  group_label?: string;
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  required_filters?: SchemaLightdashRequiredFilters;
  sql_filter?: string;
  sql_where?: string;
}
/**
 * Schema for lightdash group details
 */
export interface SchemaLightdashGroupDetails {
  /**
   * This interface was referenced by `SchemaLightdashGroupDetails`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: {
    /**
     * The label of the group
     */
    label?: string;
    /**
     * The description of the group
     */
    description?: string;
  };
}
/**
 * Schema for lightdash required attributes
 */
export interface SchemaLightdashRequiredAttributes {
  /**
   * This interface was referenced by `SchemaLightdashRequiredAttributes`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string | string[];
}
export interface SchemaLightdashMetric {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: 'thousands' | 'millions' | 'billions' | 'trillions';
  /**
   * The description that will be applied to the column in lightdash
   */
  description?: string;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  name: SchemaLightdashMetricName;
  round?: number;
  format?: 'eur' | 'gbp' | 'id' | 'km' | 'mi' | 'percent' | 'usd';
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
  tags?: SchemaModelTags;
  /**
   * The type of metric
   */
  type:
    | 'average'
    | 'boolean'
    | 'count'
    | 'count_distinct'
    | 'date'
    | 'max'
    | 'median'
    | 'min'
    | 'number'
    | 'percentile'
    | 'string'
    | 'sum';
}
/**
 * Validates schema for model-level meta. Accepts free-form custom keys (e.g. owner, owner_slack, upstream_process, freshness_sla) authored on the model root. The framework reserves two categories of keys: (1) POPULATED-RESERVED keys (metrics, portal_partition_columns, local_tags, case_sensitive, and any key spread from lightdash.table such as label / group_label / sql_filter / required_filters) are written by the framework from structured sibling fields (lightdash, tags) and will silently overwrite a user-authored value of the same name at YAML emit time -- move the value to its canonical sibling field (lightdash.*, tags) instead. Collisions are also surfaced as Warning-severity diagnostics in the Problems tab. No automatic inheritance between models; each model declares its own meta.
 */
export interface SchemaModelMeta {
  [k: string]: unknown | undefined;
}
/**
 * SQL statements to run before or after models
 */
export interface ModelSqlHooksSchemaJson {
  /**
   * Statement(s) to run after model
   */
  post?: string | [string, ...string[]];
  /**
   * Statement(s) to run before model
   */
  pre?: string | [string, ...string[]];
}
/**
 * Rollup configuration for time-grain re-aggregation
 */
export interface SchemaModelFromRollup {
  datetime_expr?: string;
  /**
   * The interval for the rollup
   */
  interval: 'day' | 'hour' | 'month' | 'year';
}
