/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates schema for model-level meta. Accepts free-form custom keys (e.g. owner, owner_slack, upstream_process, freshness_sla) authored on the model root. The framework reserves two categories of keys: (1) POPULATED-RESERVED keys (metrics, portal_partition_columns, local_tags, case_sensitive, and any key spread from lightdash.table such as label / group_label / sql_filter / required_filters) are written by the framework from structured sibling fields (lightdash, tags) and will silently overwrite a user-authored value of the same name at YAML emit time -- move the value to its canonical sibling field (lightdash.*, tags) instead. Collisions are also surfaced as Warning-severity diagnostics in the Problems tab. No automatic inheritance between models; each model declares its own meta.
 */
export interface SchemaModelMeta {
  [k: string]: unknown | undefined;
}
