/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Additional model names whose ref() edges should be forced in generated SQL via --depends_on comments (for refs hidden from dbt parse, e.g. inside {% if execute %})
 *
 * @minItems 1
 */
export type SchemaModelDependsOn = [SchemaModelRef, ...SchemaModelRef[]];
/**
 * Validate model ids
 */
export type SchemaModelRef = string;
